[package]
name = "anchor-fuzz-macro"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Fuzzing macros for anchor-test"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
